Extension { #name : 'ASTNode' }

{ #category : '*EscapeAnalysisXP' }
ASTNode >> escapeAnalyze: escapeAnalyzer [

	
]

{ #category : '*EscapeAnalysisXP' }
ASTNode >> escapeAnalyzeNode: escapeAnalyzer [

	
]

{ #category : '*EscapeAnalysisXP' }
ASTNode >> treatNode2: aNode [

	
]

{ #category : '*EscapeAnalysisXP' }
ASTNode >> treatNode: anAnlyzer [
]

{ #category : '*EscapeAnalysisXP' }
ASTNode >> treatNode: escapeAnalyzer given: trackedVariablesTable [

	
]
