Class {
	#name : 'FixtureEscapeAnalysisBrother',
	#superclass : 'Object',
	#instVars : [
		'x',
		'inst'
	],
	#category : 'EscapeAnalysisXP-Tests',
	#package : 'EscapeAnalysisXP',
	#tag : 'Tests'
}

{ #category : 'nested calls' }
FixtureEscapeAnalysisBrother >> localMessage: agr [
]

{ #category : 'nested calls' }
FixtureEscapeAnalysisBrother >> receiverMessage [
]

{ #category : 'nested calls' }
FixtureEscapeAnalysisBrother >> twoImplementationMethods [
]
